// <auto-generated />
namespace ZooApp.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedType));
        
        string IMigrationMetadata.Id
        {
            get { return "201807110332183_AddedType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
